### ISSUE TITLE
Master branch tests are not passing

### ISSUE THREAD

**Issue by meowmeowcomputers** [defi-wikis/defi-tokens-wiki#117]
Therefore, forks PR'ed to master can't pass as well

**Comment by d1ll0n** [comment]
https://github.com/defi-wikis/defi-tokens-wiki/pull/126#issuecomment-752327234

This comment has the list of tokens which are causing the errors. Their logos should either be removed or added to an exemption to the tests in order to fix this.

**Comment by d1ll0n** [comment]
There are three ways to fix this assuming the logo size tests are desired:

#128  grandfathers in the current tokens without modifying the failing tokens' logos.

#127 Deletes all the tokens with failing logos from the token-metadata directory but does not affect token-lists

#39bfd84 Bulk resizes the tokens

**Comment by meowmeowcomputers** [comment]
> There are three ways to fix this assuming the logo size tests are desired:
> 
> #128 grandfathers in the current tokens without modifying the failing tokens' logos.
> 
> #127 Deletes all the tokens with failing logos from the token-metadata directory but does not affect token-lists
> 
> #125 Bulk resizes the tokens

Thanks @d1ll0n for suggesting the fixes. I think deletion where invalid or bulk resize are probably the best approaches.
